# Dependabot configuration file
# See: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "ariyanshiputech"
    assignees:
      - "ariyanshiputech"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"

  # Enable version updates for Dart/Flutter packages (main package)
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "ariyanshiputech"
    assignees:
      - "ariyanshiputech"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    labels:
      - "dependencies"
      - "dart"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Group related updates together
    groups:
      flutter-deps:
        patterns:
          - "flutter*"
        update-types:
          - "minor"
          - "patch"
      dev-deps:
        patterns:
          - "*_test"
          - "test*"
          - "mockito"
          - "build_runner"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for critical packages to prevent breaking changes
      - dependency-name: "flutter"
        update-types: ["version-update:semver-major"]

  # Enable version updates for example app dependencies
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "ariyanshiputech"
    assignees:
      - "ariyanshiputech"
    commit-message:
      prefix: "chore(example-deps):"
      include: "scope"
    labels:
      - "dependencies"
      - "example"
      - "dart"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
