name: custom_quick_alert
description: Enterprise-grade alert dialogs for Flutter with professional UI, gradient buttons, Lottie animations, and context-free usage. Material Design 3 compliant.
version: 2.1.0
license: MIT
homepage: https://github.com/ariyanshiputech/custom_quick_alert
repository: https://github.com/ariyanshiputech/custom_quick_alert
issue_tracker: https://github.com/ariyanshiputech/custom_quick_alert/issues
documentation: https://github.com/ariyanshiputech/custom_quick_alert#readme
topics:
  - alert
  - dialog
  - popup
  - animation
  - context-free

screenshots: # Each item is a screenshot that appears on your pub.dev page.
  - description: "An example of the success alert dialog."
    path: screenshots/success_dialog.png
  - description: "An example of the error alert dialog."
    path: screenshots/error_dialog.png
  - description: "An example of the warning alert dialog."
    path: screenshots/warning_dialog.png
  - description: "An example of the info alert dialog."
    path: screenshots/info_dialog.png
  - description: "An example of the confirm alert dialog."
    path: screenshots/confirm_dialog.png
  - description: "An example of the loading alert dialog."
    path: screenshots/loading_dialog.png
  - description: "Example of custom dialog using your own widget."
    path: screenshots/custom_dialog.png

# Specifies the versions of Dart and Flutter that your package supports.
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

# ----------------- DEPENDENCIES -----------------
# These are packages that your package needs to work.
dependencies:
  # The Flutter SDK.
  flutter:
    sdk: flutter

  # For displaying Lottie animations.
  lottie: ^3.1.1

# ----------------- DEVELOPMENT DEPENDENCIES -----------------
# These are packages that are only needed for development and testing.
dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  # Provides a set of recommended lints for Flutter apps, packages, and plugins.
  mocktail: ^1.0.3
  very_good_analysis: ^9.0.0
  # For generating code, such as mocks.
flutter:
  uses-material-design: true
  assets:
    - assets/animations/confirm.json
    - assets/animations/custom.json
    - assets/animations/error.json
    - assets/animations/info.json
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/animations/warning.json
