name: 📚 Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[DOCS] "
labels: ["documentation"]
assignees: ["ariyanshiputech"]

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please describe the issue or suggestion.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README.md
        - API Documentation
        - Code Examples
        - Migration Guide
        - Installation Guide
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: Describe the documentation issue...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        - File path: docs/api/alert-types.md
        - URL: https://...
        - Section: "Quick Start"

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should we improve this documentation?
      placeholder: Describe your suggestion...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional details...
