name: ✨ Feature Request
description: Suggest a new feature or enhancement for Custom Quick Alert
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: ["ariyanshiputech"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed the following steps
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: This feature request is within the scope of Custom Quick Alert
          required: true
        - label: I have considered the impact on existing functionality
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: One-line summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        As a [user type], I want [goal] so that [benefit]...
        
        Current limitation: ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (if applicable)
      description: How should developers use this feature?
      render: dart
      placeholder: |
        // Example API usage
        CustomQuickAlert.showCustom(
          // new parameters
        );

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: Describe alternative approaches...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: checkboxes
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should this feature support?
      options:
        - label: Android
        - label: iOS
        - label: Web
        - label: Windows
        - label: macOS
        - label: Linux

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        - Screenshots or mockups
        - Links to similar implementations
        - Use cases and examples
